endpoints:
  features:
    enabled: true
server:
  port: 8080
marketplace:
  services:
    order:
      id: http://localhost:8084
      api:
        url: /v1/order/
    product:
      id: http://localhost:8083
      api:
        url: /v1/products/
        
security:
  ignored: /favicon.ico
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  oauth2:
    client:
      client-id: adminclient
      client-secret: adminsecret
      scope: read,write
      auto-approve-scopes: '.*'
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      grant_type: client_credentials
    resource:
      user-info-uri: http://localhost:9999/me
---
spring:
  profiles: cloud
marketplace:
  services:
    order:
      id: https://coffee-order-service.cfapps.io
    product:
      id: https://coffee-product-service.cfapps.io
security:
  oauth2:
    client:
      access-token-uri: https://coffee-auth-service.cfapps.io/oauth/token
      user-authorization-uri: https://coffee-auth-service.cfapps.io/oauth/authorize
    resource:
      user-info-uri: https://coffee-auth-service.cfapps.io/me
